# Generated by Django 6.0.7 on 2026-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_stock_sequence',
            },
        ),
    ]
