# Generated by Django 6.0.7 on 2026-09-12 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0029_balancesheet_master_overrides'),
        ('quotes', '0007_restore_quote_vat_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('finance', 'Finance'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='active', max_length=20)),
                ('current_stage', models.CharField(choices=[('evaluation', 'Evaluation'), ('passing', 'Passing'), ('dubai_passing', 'Dubai Passing'), ('registration_passing', 'Registration Emirate Passing'), ('insurance', 'Insurance'), ('registration', 'Registration'), ('delivery_video', 'Delivery Video'), ('completed', 'Completed')], default='evaluation', max_length=40)),
                ('registration_emirate', models.CharField(blank=True, choices=[('Dubai', 'Dubai'), ('Abu Dhabi', 'Abu Dhabi'), ('Sharjah', 'Sharjah'), ('Ajman', 'Ajman'), ('Fujairah', 'Fujairah'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Umm Al Quwain', 'Umm Al Quwain')], max_length=30, null=True)),
                ('remark', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progressions', to='finance.bankloan')),
                ('cash_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progressions', to='finance.cashdeal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_progressions', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='progression', to='quotes.quote')),
            ],
            options={
                'db_table': 'progressions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='progression_status_f8f578_idx'), models.Index(fields=['current_stage'], name='progression_current_e842c6_idx'), models.Index(fields=['source_type'], name='progression_source__73afbd_idx'), models.Index(fields=['registration_emirate'], name='progression_registr_a131ce_idx'), models.Index(fields=['created_at'], name='progression_created_9e49e7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bank_loan__isnull', False), ('cash_deal__isnull', True), ('source_type', 'finance')), models.Q(('bank_loan__isnull', True), ('cash_deal__isnull', False), ('source_type', 'cash')), _connector='OR'), name='progression_valid_source_links')],
            },
        ),
    ]
