# Generated by Django 6.0.7 on 2026-09-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0001_initial'),
        ('quotes', '0007_restore_quote_vat_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionOverrideAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('previous_stage', models.CharField(max_length=50)),
                ('new_stage', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progression_override_audits', to=settings.AUTH_USER_MODEL)),
                ('progression', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='override_audits', to='progression.progression')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progression_override_audits', to='quotes.quote')),
            ],
            options={
                'db_table': 'progression_override_audits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['progression', 'created_at'], name='progression_progres_cab535_idx'), models.Index(fields=['quote', 'created_at'], name='progression_quote_i_45360b_idx')],
            },
        ),
    ]
