# Generated by Django 6.0.7 on 2026-09-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_name', models.CharField(max_length=255)),
                ('tax_registration_number', models.CharField(blank=True, max_length=100)),
                ('showroom_address', models.TextField(blank=True)),
                ('main_contact_mobile', models.CharField(blank=True, max_length=30)),
                ('default_currency', models.CharField(default='AED', max_length=10)),
                ('default_regional_spec', models.CharField(default='GCC Specs (Standard)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='company.company')),
            ],
            options={
                'db_table': 'company_branches',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company'], name='company_bra_company_97ca1e_idx'), models.Index(fields=['is_active'], name='company_bra_is_acti_e83f4f_idx')],
            },
        ),
    ]
