# Generated by Django 6.0.7 on 2026-09-26 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='company/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='company.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_company_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['company'], name='company_doc_company_08550d_idx'), models.Index(fields=['uploaded_at'], name='company_doc_uploade_135a92_idx')],
            },
        ),
    ]
