# Generated by Django 6.0.7 on 2026-10-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_corporate_email_company_emirate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_entity_name_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
