# Generated by Django 6.0.7 on 2026-08-31 15:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0011_servicepackage_is_default'),
        ('inventory', '0009_alter_car_colour_alter_car_make_alter_car_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('current_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'quotes_sequences',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=30, unique=True)),
                ('source', models.CharField(choices=[('stock', 'Current Stock'), ('saved_emi', 'Saved EMI Calculation')], max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=30)),
                ('vehicle_stock_id', models.CharField(blank=True, max_length=50)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_variant', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('vehicle_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_chassis_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_engine_number', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('emi_bank_name', models.CharField(blank=True, max_length=150)),
                ('emi_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emi_vehicle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi_vat_enabled', models.BooleanField(blank=True, null=True)),
                ('emi_vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi_down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi_finance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi_expense_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi_tenure_years', models.PositiveIntegerField(blank=True, null=True)),
                ('emi_total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi_total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi_monthly_emi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('quote', 'Quote'), ('booked', 'Booked'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='quote', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='inventory.car')),
                ('emi_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='finance.emisheet')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('estimated_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applies', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_expenses',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='quotes_quote_n_a300f2_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='quotes_status_b396a9_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['source'], name='quotes_source_e17a08_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer_name'], name='quotes_custome_cab414_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer_mobile'], name='quotes_custome_63e1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['vehicle_stock_id'], name='quotes_vehicle_e52896_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['vehicle_chassis_number'], name='quotes_vehicle_372017_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['vehicle_engine_number'], name='quotes_vehicle_e80bed_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['created_at'], name='quotes_created_c74d71_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='quote_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', Decimal('0.00'))), name='quote_deposit_non_negative'),
        ),
        migrations.AddIndex(
            model_name='quoteexpense',
            index=models.Index(fields=['quote', 'expense_type'], name='quote_expen_quote_i_7daab0_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteexpense',
            index=models.Index(fields=['expense_type'], name='quote_expen_expense_0d05a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='quoteexpense',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_min__isnull', True), ('estimated_min__gte', Decimal('0.00')), _connector='OR'), name='quote_expense_estimated_min_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quoteexpense',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_max__isnull', True), ('estimated_max__gte', Decimal('0.00')), _connector='OR'), name='quote_expense_estimated_max_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quoteexpense',
            constraint=models.CheckConstraint(condition=models.Q(('actual_amount__isnull', True), ('actual_amount__gte', Decimal('0.00')), _connector='OR'), name='quote_expense_actual_non_negative'),
        ),
    ]
