# Generated by Django 6.0.7 on 2026-09-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Finance', 'Finance')], max_length=30),
        ),
    ]
