# Generated by Django 6.0.7 on 2026-09-03 07:45

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_emisheet_base_amount'),
        ('inventory', '0009_alter_car_colour_alter_car_make_alter_car_model_and_more'),
        ('quotes', '0002_alter_quote_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quote',
            name='quote_price_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='quote',
            name='quote_deposit_non_negative',
        ),
        migrations.AddField(
            model_name='quote',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='quote',
            name='extra_down_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('down_payment__gte', Decimal('0.00'))), name='quote_down_payment_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('extra_down_payment__gte', Decimal('0.00'))), name='quote_extra_down_payment_non_negative'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='deposit_amount',
        ),
    ]
