# Generated by Django 6.0.7 on 2026-09-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('quotes', '0003_remove_quote_quote_price_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customers.customer'),
        ),
    ]
