# Generated by Django 6.0.7 on 2026-09-10 08:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='quote',
            name='vat_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
