# Generated by Django 6.0.7 on 2026-09-10 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0002_insurance_renewal_status_insurancepolicy'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('delivery_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('vehicle_chassis_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_engine_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, editable=False)),
                ('unit', models.CharField(default='Car', editable=False, max_length=30)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_signature', models.TextField(blank=True)),
                ('buyer_signature_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='insurance.insurance')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_note', to='quotes.quote')),
            ],
            options={
                'db_table': 'delivery_note_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
