# Generated by Django 6.0.7 on 2026-10-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_company_name_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='category',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('emirates_id', 'Emirates ID'), ('bank_lpo', 'Bank LPO'), ('company_trade_license', 'Company Trade License')], max_length=30),
        ),
    ]
