# Generated by Django 6.0.7 on 2026-09-19 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('customers', '0002_customer_email'),
        ('inventory', '0018_procurementcheck'),
        ('quotes', '0007_restore_quote_vat_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('rta_date', models.DateField(default=django.utils.timezone.localdate)),
                ('first_party_name', models.CharField(max_length=255)),
                ('first_party_role', models.CharField(choices=[('COMPANY', 'Company'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('OTHER', 'Other')], max_length=20)),
                ('second_party_name', models.CharField(max_length=255)),
                ('second_party_role', models.CharField(choices=[('COMPANY', 'Company'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('OTHER', 'Other')], max_length=20)),
                ('second_party_mobile', models.CharField(blank=True, max_length=30)),
                ('company_legal_name', models.CharField(max_length=255)),
                ('trade_license_number', models.CharField(blank=True, max_length=100)),
                ('company_address', models.TextField(blank=True)),
                ('vehicle_stock_id', models.CharField(blank=True, max_length=50)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_variant', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('vehicle_country_of_manufacture', models.CharField(blank=True, max_length=100)),
                ('vehicle_chassis_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_engine_number', models.CharField(blank=True, max_length=100)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rta_records', to='company.companybranch')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rta_records', to='inventory.car')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rta_records', to='company.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rta_records', to='customers.customer')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rta_records', to='quotes.quote')),
            ],
            options={
                'db_table': 'rta_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_type'], name='rta_records_record__3579dc_idx'), models.Index(fields=['status'], name='rta_records_status_65b98b_idx'), models.Index(fields=['rta_date'], name='rta_records_rta_dat_d18b69_idx'), models.Index(fields=['quote'], name='rta_records_quote_i_8f4c57_idx'), models.Index(fields=['car'], name='rta_records_car_id_8be78d_idx'), models.Index(fields=['customer'], name='rta_records_custome_6d46a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('quote', 'record_type'), name='unique_rta_record_per_quote_type')],
            },
        ),
    ]
