# Generated by Django 6.0.7 on 2026-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtarecord',
            name='first_party_signatory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rtarecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rtarecord',
            name='rta_reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rtarecord',
            name='second_party_signatory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rtarecord',
            name='supplier_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rtarecord',
            name='supplier_mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rtarecord',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rtarecord',
            name='supplier_trade_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
