# Generated by Django 6.0.7 on 2026-09-25 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('customers', '0002_customer_email'),
        ('inventory', '0019_migrate_legacy_possession_documents'),
        ('quotes', '0007_restore_quote_vat_columns'),
        ('rta', '0002_rtarecord_first_party_signatory_name_rtarecord_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTADocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('SUPPLIER_DOCUMENT', 'Supplier Document'), ('PURCHASE_AGREEMENT', 'Purchase Agreement'), ('SALE_AGREEMENT', 'Sale Agreement'), ('OTHER', 'Other')], max_length=40)),
                ('file', models.FileField(upload_to='rta_documents/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rta_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='rtarecord',
            name='unique_rta_record_per_quote_type',
        ),
        migrations.AlterField(
            model_name='rtarecord',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rta_records', to='quotes.quote'),
        ),
        migrations.AddConstraint(
            model_name='rtarecord',
            constraint=models.UniqueConstraint(condition=models.Q(('quote__isnull', False), ('record_type', 'SALE')), fields=('quote', 'record_type'), name='unique_sale_rta_per_quote'),
        ),
        migrations.AddConstraint(
            model_name='rtarecord',
            constraint=models.UniqueConstraint(condition=models.Q(('record_type', 'PURCHASE')), fields=('car', 'record_type'), name='unique_purchase_rta_per_car'),
        ),
        migrations.AddField(
            model_name='rtadocument',
            name='rta_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rta.rtarecord'),
        ),
        migrations.AddField(
            model_name='rtadocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_rta_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
