# Generated by Django 6.0.7 on 2026-10-01 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_legal_entity_name_ar'),
        ('rta', '0003_rtadocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale')], max_length=20)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rta_templates', to='company.company')),
            ],
            options={
                'db_table': 'rta_templates',
                'ordering': ['company_id', 'record_type'],
                'indexes': [models.Index(fields=['company'], name='rta_templat_company_b39334_idx'), models.Index(fields=['record_type'], name='rta_templat_record__20393a_idx'), models.Index(fields=['is_active'], name='rta_templat_is_acti_5668eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'record_type'), name='unique_rta_template_per_company_type')],
            },
        ),
    ]
