# Generated by Django 6.0.7 on 2026-08-18 08:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0009_alter_car_colour_alter_car_make_alter_car_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmiSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_number', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=30)),
                ('vehicle_stock_id', models.CharField(max_length=50)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_variant', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(max_length=150)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_enabled', models.BooleanField(default=False)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('price_after_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_years', models.PositiveIntegerField()),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_emi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emi_sheets', to='finance.bank')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emi_sheets', to='inventory.car')),
            ],
            options={
                'db_table': 'finance_emi_sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmiExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('evaluation', 'Evaluation'), ('bank_process', 'Bank Process'), ('rta', 'RTA'), ('insurance', 'Insurance'), ('registration', 'Registration')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emi_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.emisheet')),
            ],
            options={
                'db_table': 'finance_emi_expenses',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='emisheet',
            index=models.Index(fields=['emi_number'], name='finance_emi_emi_num_2ba216_idx'),
        ),
        migrations.AddIndex(
            model_name='emisheet',
            index=models.Index(fields=['customer_name'], name='finance_emi_custome_a49130_idx'),
        ),
        migrations.AddIndex(
            model_name='emisheet',
            index=models.Index(fields=['customer_mobile'], name='finance_emi_custome_815b98_idx'),
        ),
        migrations.AddIndex(
            model_name='emisheet',
            index=models.Index(fields=['vehicle_stock_id'], name='finance_emi_vehicle_19017d_idx'),
        ),
        migrations.AddIndex(
            model_name='emisheet',
            index=models.Index(fields=['created_at'], name='finance_emi_created_e54187_idx'),
        ),
    ]
