# Generated by Django 6.0.7 on 2026-08-18 11:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__gte', Decimal('0.00'))), name='bank_interest_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.CheckConstraint(condition=models.Q(('is_cash', False), ('interest_rate', Decimal('0.00')), _connector='OR'), name='cash_bank_zero_interest'),
        ),
    ]
