# Generated by Django 6.0.7 on 2026-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bank_bank_interest_rate_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmiSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('current_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'finance_emi_sequences',
            },
        ),
    ]
