# Generated by Django 6.0.7 on 2026-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_emisequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisheet',
            name='manual_rate_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='vehicle_chassis_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='vehicle_engine_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='vehicle_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
