# Generated by Django 6.0.7 on 2026-08-24 14:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_emisheet_manual_rate_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisheet',
            name='bank_processing_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='evaluation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='evaluation_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='insurance_band_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='registration_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='rta_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='service_package_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='service_package_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='ExpensePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('expense_type', models.CharField(choices=[('evaluation', 'Evaluation'), ('rta', 'RTA'), ('registration', 'Registration')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_expense_presets',
                'ordering': ['expense_type', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='expense_preset_amount_non_negative'), models.UniqueConstraint(fields=('expense_type', 'name'), name='unique_expense_preset_type_name')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('minimum_vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_insurance_bands',
                'ordering': ['minimum_vehicle_price'],
                'constraints': [models.CheckConstraint(condition=models.Q(('minimum_vehicle_price__gte', Decimal('0.00'))), name='insurance_band_min_price_non_negative'), models.CheckConstraint(condition=models.Q(('maximum_vehicle_price__gt', models.F('minimum_vehicle_price'))), name='insurance_band_max_greater_than_min'), models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='insurance_band_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_service_packages',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='service_package_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='BankProcessingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_configuration', to='finance.bank')),
            ],
            options={
                'db_table': 'finance_bank_processing_configurations',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='bank_processing_amount_non_negative')],
            },
        ),
    ]
