# Generated by Django 6.0.7 on 2026-08-24 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_emisheet_bank_processing_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emiexpense',
            name='expense_type',
            field=models.CharField(choices=[('evaluation', 'Evaluation'), ('bank_process', 'Bank Process'), ('rta', 'RTA'), ('insurance', 'Insurance'), ('registration', 'Registration'), ('service_package', 'Service Package')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emisheet',
            name='tenure_years',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expensepreset',
            name='expense_type',
            field=models.CharField(choices=[('evaluation', 'Evaluation'), ('rta', 'RTA'), ('registration', 'Registration'), ('service_package', 'Service Package')], max_length=30),
        ),
    ]
