# Generated by Django 6.0.7 on 2026-08-25 06:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_emiexpense_expense_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankprocessingconfiguration',
            name='bank_processing_amount_non_negative',
        ),
        migrations.AddField(
            model_name='bankprocessingconfiguration',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('540.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='bankprocessingconfiguration',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=5),
        ),
        migrations.AddField(
            model_name='emiexpense',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddConstraint(
            model_name='bankprocessingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', Decimal('0.00'))), name='bank_processing_percentage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bankprocessingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_amount__gte', Decimal('0.00'))), name='bank_processing_minimum_amount_non_negative'),
        ),
        migrations.RemoveField(
            model_name='bankprocessingconfiguration',
            name='amount',
        ),
    ]
