# Generated by Django 6.0.7 on 2026-08-25 11:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_bankprocessingconfiguration_bank_processing_amount_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisheet',
            name='emi_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='expense_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
