# Generated by Django 6.0.7 on 2026-08-25 15:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_emisheet_emi_principal_emisheet_expense_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankprocessingconfiguration',
            name='application_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='banker_application_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='driving_license',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='expense_selection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='include_other_expenses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='insurance_surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='registration_dubai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='service_package_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emisheet',
            name='unit_price_after_down_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='expensepreset',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage_minimum', 'Percentage with minimum'), ('conditional', 'Conditional value')], default='fixed', max_length=30),
        ),
        migrations.AddField(
            model_name='expensepreset',
            name='condition_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='expensepreset',
            name='condition_value',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='expensepreset',
            name='minimum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expensepreset',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='bankprocessingconfiguration',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('540.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='bankprocessingconfiguration',
            name='percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.2500'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='emiexpense',
            name='expense_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='expensepreset',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='expensepreset',
            name='expense_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='insuranceband',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='insuranceband',
            name='maximum_vehicle_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='insuranceband',
            name='minimum_vehicle_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='bankprocessingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('application_charge__gte', Decimal('0.00'))), name='bank_processing_application_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='expensepreset',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), ('percentage__gte', Decimal('0.00')), _connector='OR'), name='expense_preset_percentage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='expensepreset',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_amount__isnull', True), ('minimum_amount__gte', Decimal('0.00')), _connector='OR'), name='expense_preset_minimum_non_negative'),
        ),
    ]
