# Generated by Django 6.0.7 on 2026-08-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_seed_finance_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
