# Generated by Django 6.0.7 on 2026-09-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_emisheet_base_amount_emisheet_car_value_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisheet',
            name='base_amount',
        ),
    ]
