# Generated by Django 6.0.7 on 2026-09-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0013_remove_emisheet_base_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisheet',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emi_sheets', to='customers.customer'),
        ),
    ]
