# Generated by Django 6.0.7 on 2026-09-04 16:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_emisheet_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceband',
            name='no_license_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='insuranceband',
            constraint=models.CheckConstraint(condition=models.Q(('no_license_surcharge__gte', Decimal('0.00'))), name='insurance_band_no_license_surcharge_non_negative'),
        ),
    ]
