# Generated by Django 6.0.7 on 2026-09-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0015_insuranceband_no_license_surcharge_and_more'),
        ('inventory', '0010_car_actual_mileage_car_service_location_and_more'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=30)),
                ('vehicle_stock_id', models.CharField(max_length=50)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_variant', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('vehicle_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_chassis_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_engine_number', models.CharField(blank=True, max_length=100)),
                ('requested_finance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('approved_finance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_loans', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_loans', to='finance.bank')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_loans', to='inventory.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_loans', to='customers.customer')),
                ('emi_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_loans', to='finance.emisheet')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_loan', to='quotes.quote')),
            ],
            options={
                'db_table': 'finance_bank_loans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application_status'], name='finance_ban_applica_f96db4_idx'), models.Index(fields=['status'], name='finance_ban_status_93bad0_idx'), models.Index(fields=['priority'], name='finance_ban_priorit_7de85e_idx'), models.Index(fields=['bank'], name='finance_ban_bank_id_1b6f52_idx'), models.Index(fields=['customer_name'], name='finance_ban_custome_f3c8fe_idx'), models.Index(fields=['vehicle_stock_id'], name='finance_ban_vehicle_1e8a8b_idx'), models.Index(fields=['created_at'], name='finance_ban_created_55fee9_idx')],
            },
        ),
    ]
