# Generated by Django 6.0.7 on 2026-09-08 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_bankloan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoanFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='finance.bankloan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_loan_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_bank_loan_follow_ups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bank_loan', '-created_at'], name='finance_ban_bank_lo_a806df_idx'), models.Index(fields=['created_at'], name='finance_ban_created_3c2b43_idx')],
            },
        ),
    ]
