# Generated by Django 6.0.7 on 2026-09-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_bankloanfollowup'),
        ('inventory', '0010_car_actual_mileage_car_service_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloan',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_loans', to='inventory.car'),
        ),
    ]
