# Generated by Django 6.0.7 on 2026-09-08 08:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0018_alter_bankloan_car'),
        ('inventory', '0010_car_actual_mileage_car_service_location_and_more'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=30)),
                ('vehicle_stock_id', models.CharField(blank=True, max_length=50)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_variant', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('vehicle_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_chassis_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_engine_number', models.CharField(blank=True, max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('evaluation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('advance_received', 'Advance Received'), ('payment_pending', 'Payment Pending'), ('ready_for_delivery', 'Ready for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=30)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_deals', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_deals', to='inventory.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_deals', to='customers.customer')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_deal', to='quotes.quote')),
            ],
            options={
                'db_table': 'finance_cash_deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='finance_cas_status_9a9930_idx'), models.Index(fields=['customer_name'], name='finance_cas_custome_8c052c_idx'), models.Index(fields=['customer_mobile'], name='finance_cas_custome_430e08_idx'), models.Index(fields=['vehicle_stock_id'], name='finance_cas_vehicle_4a4c5b_idx'), models.Index(fields=['vehicle_chassis_number'], name='finance_cas_vehicle_4d30f7_idx'), models.Index(fields=['created_at'], name='finance_cas_created_852c06_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('selling_price__gte', Decimal('0.00'))), name='cash_deal_selling_price_non_negative'), models.CheckConstraint(condition=models.Q(('evaluation__gte', Decimal('0.00'))), name='cash_deal_evaluation_non_negative'), models.CheckConstraint(condition=models.Q(('advance_amount__gte', Decimal('0.00'))), name='cash_deal_advance_non_negative'), models.CheckConstraint(condition=models.Q(('balance_amount__gte', Decimal('0.00'))), name='cash_deal_balance_non_negative')],
            },
        ),
    ]
