# Generated by Django 6.0.7 on 2026-09-08 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_cashdeal'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankloan',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='application_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='expected_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='relationship_manager',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankloanfollowup',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='application_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('documents_collection', 'Documents Collection'), ('applied', 'Applied'), ('payslip_pending', 'Payslip Pending'), ('email_phone_verification', 'Email/Phone Verification'), ('advance_paid', 'Advance Paid'), ('waiting_dda', 'Waiting DDA'), ('registration', 'Registration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('change_of_car', 'Change of Car')], default='not_submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_loans', to='quotes.quote'),
        ),
    ]
