# Generated by Django 6.0.7 on 2026-09-09 08:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0022_alter_cashdeal_agent'),
        ('inventory', '0010_car_actual_mileage_car_service_location_and_more'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('direction', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('company_on_behalf', 'Company On Behalf')], max_length=30)),
                ('category', models.CharField(choices=[('advance', 'Advance'), ('final_payment', 'Final Payment'), ('additional_payment', 'Additional Payment'), ('down_payment', 'Down Payment'), ('evaluation', 'Evaluation'), ('bank_processing', 'Bank Processing'), ('rta_passing', 'RTA Passing'), ('registration', 'Registration'), ('insurance', 'Insurance'), ('service_package', 'Service Package'), ('warranty_service_contract', 'Warranty & Service Contract'), ('export_transfer', 'Export / Transfer'), ('other', 'Other')], max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('transaction_date', models.DateField()),
                ('source', models.CharField(default='cash_receipt', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='inventory.car')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='customers.customer')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='quotes.quote')),
            ],
            options={
                'db_table': 'finance_cash_receipts',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['customer'], name='finance_cas_custome_ab5b9a_idx'), models.Index(fields=['quote'], name='finance_cas_quote_i_bb3b82_idx'), models.Index(fields=['car'], name='finance_cas_car_id_e8c79c_idx'), models.Index(fields=['direction'], name='finance_cas_directi_9fe3a0_idx'), models.Index(fields=['category'], name='finance_cas_categor_53fefb_idx'), models.Index(fields=['payment_method'], name='finance_cas_payment_7405cd_idx'), models.Index(fields=['transaction_date'], name='finance_cas_transac_ee39c7_idx'), models.Index(fields=['created_at'], name='finance_cas_created_8a4c92_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='cash_receipt_amount_positive')],
            },
        ),
    ]
