# Generated by Django 6.0.7 on 2026-09-09 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0023_cashreceipt'),
        ('inventory', '0010_car_actual_mileage_car_service_location_and_more'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheets', to='inventory.car')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheets_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheets', to='customers.customer')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheet', to='quotes.quote')),
            ],
            options={
                'db_table': 'finance_balance_sheets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='balance_sheet_customer_idx'), models.Index(fields=['car'], name='balance_sheet_car_idx'), models.Index(fields=['created_at'], name='balance_sheet_created_idx')],
            },
        ),
    ]
