# Generated by Django 6.0.7 on 2026-09-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_balancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.cashreceipt'),
        ),
    ]
