# Generated by Django 6.0.7 on 2026-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_cashreceipt_reversal_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
