# Generated by Django 6.0.7 on 2026-09-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_alter_cashreceipt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='category',
            field=models.CharField(max_length=80),
        ),
    ]
