# Generated by Django 6.0.7 on 2026-09-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_cashreceipt_category'),
        ('quotes', '0004_quote_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='emi_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='finance.emiexpense'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='quote_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='quotes.quoteexpense'),
        ),
    ]
