# Generated by Django 6.0.7 on 2026-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_cashreceipt_emi_expense_cashreceipt_quote_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='master_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
