# Generated by Django 6.0.7 on 2026-07-31 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_id', models.CharField(max_length=20, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('chassis_number', models.CharField(blank=True, max_length=100)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('least_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('upcoming', 'Upcoming'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('in_service', 'In Service'), ('in_house', 'In House')], default='available', max_length=20)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('own_purchase', 'Own Purchase')], default='own_purchase', max_length=30)),
                ('highlight_public', models.BooleanField(default=False)),
                ('possession_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.car')),
            ],
            options={
                'db_table': 'car_expenses',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photos/')),
                ('is_cover', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.car')),
            ],
            options={
                'db_table': 'car_images',
                'ordering': ['-is_cover', 'id'],
            },
        ),
    ]
