# Generated by Django 6.0.7 on 2026-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_car_asking_price_alter_car_least_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='variant',
            field=models.CharField(max_length=100),
        ),
    ]
