# Generated by Django 6.0.7 on 2026-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_car_colour_alter_car_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='supplier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
