# Generated by Django 6.0.7 on 2026-08-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_car_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='source_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='source',
            field=models.CharField(choices=[('own_purchase', 'Own Purchase'), ('fly_wheel', 'Fly Wheel'), ('park_and_sale', 'Park and Sale'), ('auction', 'Auction'), ('trade_in', 'Trade In'), ('other', 'Other')], default='own_purchase', max_length=30),
        ),
    ]
