# Generated by Django 6.0.7 on 2026-08-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_car_source_specify_alter_car_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['stock_id'], name='cars_stock_i_b173ec_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status'], name='cars_status_5ca548_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['source'], name='cars_source_a87807_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['supplier'], name='cars_supplie_dff770_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make'], name='cars_make_2a151c_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['model'], name='cars_model_af2c08_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='cars_year_6f2c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['created_at'], name='cars_created_7f4bc6_idx'),
        ),
    ]
