# Generated by Django 6.0.7 on 2026-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_car_cars_stock_i_b173ec_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['-is_cover', 'id', 'display_order']},
        ),
        migrations.AddField(
            model_name='carimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
