# Generated by Django 6.0.7 on 2026-08-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_carimage_options_alter_car_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='variant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
