# Generated by Django 6.0.7 on 2026-09-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_car_colour_alter_car_make_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='actual_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='service_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('upcoming', 'Upcoming'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('sold', 'Sold'), ('in_service', 'In Service'), ('in_house', 'In House')], default='available', max_length=20),
        ),
    ]
