# Generated by Django 6.0.7 on 2026-09-11 20:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_car_actual_mileage_car_service_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('approved_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_price_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_price_requests', to='inventory.car')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_price_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_special_price_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', 'status'], name='inventory_s_car_id_55218e_idx'), models.Index(fields=['requested_by'], name='inventory_s_request_e381b5_idx'), models.Index(fields=['status'], name='inventory_s_status_c4dfbb_idx'), models.Index(fields=['created_at'], name='inventory_s_created_737f4a_idx')],
            },
        ),
    ]
