# Generated by Django 6.0.7 on 2026-09-11 20:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_balancesheet_master_overrides'),
        ('inventory', '0011_specialpricerequest'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpricerequest',
            name='emi_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_price_requests', to='finance.emisheet'),
        ),
        migrations.AddField(
            model_name='specialpricerequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialpricerequest',
            name='inventory_asked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='specialpricerequest',
            name='inventory_vehicle_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='specialpricerequest',
            name='least_selling_price_at_request',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='specialpricerequest',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_price_requests', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='specialpricerequest',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialpricerequest',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_price_requests_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialpricerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('used', 'Used')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='specialpricerequest',
            index=models.Index(fields=['quote'], name='inventory_s_quote_i_a57ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='specialpricerequest',
            index=models.Index(fields=['emi_sheet'], name='inventory_s_emi_she_e347d5_idx'),
        ),
        migrations.AddIndex(
            model_name='specialpricerequest',
            index=models.Index(fields=['expires_at'], name='inventory_s_expires_1cb075_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialpricerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('car',), name='unique_pending_special_price_per_car'),
        ),
    ]
