# Generated by Django 6.0.7 on 2026-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_specialpricerequest_emi_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV (Sport Utility Vehicle)'), ('hatchback', 'Hatchback'), ('crossover', 'Crossover'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup_truck', 'Pickup Truck'), ('other', 'Other')], max_length=100),
        ),
    ]
