# Generated by Django 6.0.7 on 2026-09-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_vehicledocument_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[('POSSESSION', 'Possession'), ('RTA_PASSING', 'RTA Passing'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
