# Generated by Django 6.0.7 on 2026-09-19 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_vehicledocument_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDemand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('make', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('colour', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_car_demands', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_car_demands', to=settings.AUTH_USER_MODEL)),
                ('matched_vehicles', models.ManyToManyField(blank=True, related_name='car_demands', to='inventory.car')),
            ],
            options={
                'db_table': 'car_demands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='car_demands_status_dc8e99_idx'), models.Index(fields=['phone'], name='car_demands_phone_7dddbe_idx'), models.Index(fields=['make', 'model'], name='car_demands_make_e45b4d_idx'), models.Index(fields=['agent'], name='car_demands_agent_i_6cb39b_idx'), models.Index(fields=['created_by'], name='car_demands_created_b74743_idx')],
            },
        ),
    ]
