# Generated by Django 6.0.7 on 2026-09-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_cardemand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(blank=True, max_length=255)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('range_trim_code', models.CharField(blank=True, max_length=100)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=255)),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('van', 'Van'), ('other', 'Other')], max_length=30)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('recorded_accidents', models.PositiveIntegerField(blank=True, null=True)),
                ('no_accidents', models.BooleanField(default=False)),
                ('condition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_check', to='inventory.car')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chassis_number'], name='procurement_chassis_9b6373_idx'), models.Index(fields=['make', 'model'], name='procurement_make_fcb55d_idx'), models.Index(fields=['model_year'], name='procurement_model_y_730c0d_idx'), models.Index(fields=['checked_by'], name='procurement_checked_b2eb17_idx')],
            },
        ),
    ]
