# Generated by Django 6.0.7 on 2026-09-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companydocument'),
        ('inventory', '0019_migrate_legacy_possession_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_cars', to='company.companybranch'),
        ),
    ]
