# Generated by Django 6.0.7 on 2026-09-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_car_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[('POSSESSION', 'Possession'), ('RTA_PASSING', 'RTA Passing'), ('INVOICE', 'Invoice'), ('MULKIYA', 'Mulkiya / Registration Card'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
