# Generated by Django 6.0.7 on 2026-10-05 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_vehicledocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpricerequest',
            name='inventory_purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
