# Generated by Django 6.0.7 on 2026-09-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0029_balancesheet_master_overrides'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=30)),
                ('vehicle_stock_id', models.CharField(blank=True, max_length=50)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('vehicle_chassis_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_engine_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=30)),
                ('application_status', models.CharField(choices=[('applied', 'Applied'), ('documents_pending', 'Documents Pending'), ('approved', 'Approved')], default='applied', max_length=30)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_loan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance', to='finance.bankloan')),
                ('cash_deal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance', to='finance.cashdeal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_records', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='insurance', to='quotes.quote')),
            ],
            options={
                'db_table': 'insurance_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
