# Generated by Django 6.0.7 on 2026-09-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='renewal_status',
            field=models.CharField(blank=True, choices=[('informed_customer', 'Informed Customer'), ('applied_new', 'Applied New'), ('follow_up', 'Follow Up'), ('not_interested', 'Not Interested'), ('new_insurance_approved', 'New Insurance Approved')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField()),
                ('policy_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_cycles', to='insurance.insurance')),
            ],
            options={
                'db_table': 'insurance_policy_cycles',
                'ordering': ['cycle_number'],
                'constraints': [models.UniqueConstraint(fields=('insurance', 'cycle_number'), name='unique_insurance_policy_cycle'), models.UniqueConstraint(fields=('policy_number',), name='unique_insurance_policy_number')],
            },
        ),
    ]
