from django.urls import path

from apps.inventory import views

urlpatterns = [
    path("vehicles/", views.VehicleListCreateAPIView.as_view(), name="vehicle-list"),
    path("vehicles/export/", views.VehicleExportAPIView.as_view(), name="vehicle-export"),
    path(
        "vehicles/bulk-import/",
        views.VehicleBulkImportAPIView.as_view(),
        name="vehicle-bulk-import",
    ),
    path(
        "vehicles/<uuid:vehicle_id>/",
        views.VehicleDetailAPIView.as_view(),
        name="vehicle-detail",
    ),
    path(
        "vehicles/<uuid:vehicle_id>/publish/",
        views.VehiclePublishAPIView.as_view(),
        name="vehicle-publish",
    ),
    path(
        "vehicles/<uuid:vehicle_id>/feature/",
        views.VehicleFeatureAPIView.as_view(),
        name="vehicle-feature",
    ),
    path(
        "vehicles/<uuid:vehicle_id>/status/",
        views.VehicleStatusAPIView.as_view(),
        name="vehicle-status",
    ),
    path(
        "vehicles/<uuid:vehicle_id>/images/",
        views.VehicleImageListCreateAPIView.as_view(),
        name="vehicle-images",
    ),
    path(
        "vehicle-images/<uuid:image_id>/",
        views.VehicleImageDetailAPIView.as_view(),
        name="vehicle-image-detail",
    ),
    path(
        "vehicles/<uuid:vehicle_id>/documents/",
        views.VehicleDocumentListCreateAPIView.as_view(),
        name="vehicle-documents",
    ),
    path(
        "vehicle-documents/<uuid:document_id>/",
        views.VehicleDocumentDetailAPIView.as_view(),
        name="vehicle-document-detail",
    ),
    path(
        "lookups/manufacturers/",
        views.ManufacturerListAPIView.as_view(),
        name="manufacturer-list",
    ),
    path(
        "lookups/models/",
        views.VehicleModelListAPIView.as_view(),
        name="vehicle-model-list",
    ),
    path(
        "lookups/generations/",
        views.GenerationListAPIView.as_view(),
        name="generation-list",
    ),
    path(
        "lookups/variants/",
        views.VariantListAPIView.as_view(),
        name="variant-list",
    ),
    path(
        "lookups/fuel-types/",
        views.FuelTypeListAPIView.as_view(),
        name="fuel-type-list",
    ),
    path(
        "lookups/transmissions/",
        views.TransmissionListAPIView.as_view(),
        name="transmission-list",
    ),
    path(
        "lookups/drive-types/",
        views.DriveTypeListAPIView.as_view(),
        name="drive-type-list",
    ),
    path(
        "lookups/body-types/",
        views.BodyTypeListAPIView.as_view(),
        name="body-type-list",
    ),
    path(
        "lookups/engine-types/",
        views.EngineTypeListAPIView.as_view(),
        name="engine-type-list",
    ),
    path("lookups/colors/", views.ColorListAPIView.as_view(), name="color-list"),
    path(
        "lookups/interior-colors/",
        views.InteriorColorListAPIView.as_view(),
        name="interior-color-list",
    ),
    path(
        "lookups/statuses/",
        views.VehicleStatusListAPIView.as_view(),
        name="vehicle-status-list",
    ),
]
