# Generated by Django 6.0.7 on 2026-09-11 16:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('job_role', models.CharField(choices=[('SALES_EXECUTIVE', 'Sales Executive'), ('PROCUREMENT', 'Procurement'), ('ACCOUNTS', 'Accounts'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager')], max_length=30)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('leave_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='staff_status_c91b08_idx'), models.Index(fields=['job_role'], name='staff_job_rol_a41b3b_idx'), models.Index(fields=['name'], name='staff_name_ede581_idx')],
            },
        ),
    ]
