# Generated by Django 6.0.7 on 2026-09-27 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'Leave'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_attendance',
                'ordering': ['-attendance_date', 'staff_id'],
                'indexes': [models.Index(fields=['staff', 'attendance_date'], name='staff_atten_staff_i_0ec976_idx'), models.Index(fields=['attendance_date'], name='staff_atten_attenda_ad92ad_idx'), models.Index(fields=['status'], name='staff_atten_status_d7bbff_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'attendance_date'), name='unique_staff_attendance_date')],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_year', models.PositiveIntegerField()),
                ('payroll_month', models.PositiveSmallIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_records', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_payroll',
                'ordering': ['-payroll_year', '-payroll_month', 'staff_id'],
                'indexes': [models.Index(fields=['staff', 'payroll_year', 'payroll_month'], name='staff_payro_staff_i_04fdd1_idx'), models.Index(fields=['payroll_year', 'payroll_month'], name='staff_payro_payroll_372f5b_idx'), models.Index(fields=['status'], name='staff_payro_status_c4638f_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'payroll_year', 'payroll_month'), name='unique_staff_payroll_period'), models.CheckConstraint(condition=models.Q(('payroll_month__gte', 1), ('payroll_month__lte', 12)), name='valid_payroll_month')],
            },
        ),
    ]
