# Generated by Django 6.0.7 on 2026-09-10 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0002_insurance_renewal_status_insurancepolicy'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_number', models.CharField(max_length=50, unique=True)),
                ('proforma_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('finance', 'Finance'), ('cash', 'Cash')], max_length=20)),
                ('bank_financed_by', models.CharField(blank=True, max_length=255)),
                ('lpo', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=30)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_chassis_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_engine_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_finance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='insurance.insurance')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='quotes.quote')),
            ],
            options={
                'db_table': 'proforma_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
