# Generated by Django 6.0.7 on 2026-09-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
        ('quotes', '0004_quote_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proforma', to='quotes.quote'),
        ),
    ]
