# Generated by Django 6.0.7 on 2026-09-10 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurance_renewal_status_insurancepolicy'),
        ('proforma', '0002_alter_proforma_quote'),
        ('quotes', '0004_quote_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proforma',
            constraint=models.CheckConstraint(condition=models.Q(('vehicle_price__gte', 0)), name='proforma_vehicle_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proforma',
            constraint=models.CheckConstraint(condition=models.Q(('down_payment__gte', 0)), name='proforma_down_payment_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proforma',
            constraint=models.CheckConstraint(condition=models.Q(('vat__gte', 0)), name='proforma_vat_non_negative'),
        ),
    ]
