# Generated by Django 6.0.7 on 2026-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0003_proforma_proforma_vehicle_price_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='proforma_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
