# Generated by Django 6.0.7 on 2026-09-11 16:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('enquiry_source', models.CharField(choices=[('Direct', 'Direct'), ('Dubizzle', 'Dubizzle'), ('Dubizzle (Import)', 'Dubizzle (Import)'), ('Facebook', 'Facebook'), ('Google Ads', 'Google Ads'), ('Import', 'Import'), ('Instagram', 'Instagram'), ('Insurance', 'Insurance'), ('Interakt', 'Interakt'), ('Referral', 'Referral'), ('Website', 'Website'), ('WhatsApp', 'WhatsApp')], max_length=50)),
                ('enquiry_status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Cash Deal', 'Cash Deal'), ('Follow-Up / Negotiation', 'Follow-Up / Negotiation'), ('Test Drive Booked', 'Test Drive Booked'), ('Qualified', 'Qualified'), ('4k Less', '4k Less'), ('Below 20k Budget', 'Below 20k Budget'), ('Unqualified', 'Unqualified')], default='New', max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('insurance', models.CharField(blank=True, max_length=255)),
                ('type_of_car', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('mode_of_payment', models.CharField(blank=True, max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('lead_from', models.CharField(blank=True, max_length=255)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='staff.staff')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='leads.lead')),
                ('new_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('previous_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'db_table': 'lead_assignment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['enquiry_status'], name='leads_enquiry_512a64_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['enquiry_source'], name='leads_enquiry_4e9d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_assigne_c5180e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_by'], name='leads_created_dee243_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_activity_at'], name='leads_last_ac_87ffc8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_number'], name='leads_phone_n_99abde_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='lead_activi_lead_id_d58c46_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['created_by'], name='lead_activi_created_e1c1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignmenthistory',
            index=models.Index(fields=['lead', '-created_at'], name='lead_assign_lead_id_2a0225_idx'),
        ),
    ]
